// DOM_CONTENT_LOADED GETS EXECUTED ONCE THE BASIC HTML DOC IS LOADED AND ITS PARSING HAS TAKEN PLACE.
// THIS EVENT DOES NOT WAIT FOR COMPLETION OF LOADING OF ADD-ONS(STYLESHEETS, IMAGES ETC)
document.addEventListener("DOMContentLoaded", function(){  
    // CARD OPTIONS
})